# Generated by Django 5.2.13 on 2026-04-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_private_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
